# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: moneda.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmoneda.proto\"5\n\x12message_parameters\x12\x0e\n\x06moneda\x18\x01 \x01(\t\x12\x0f\n\x07periodo\x18\x02 \x01(\t\"\x06\n\x04ping\"\x12\n\x03\x41\x43K\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\x32V\n\nParameters\x12\x1a\n\x0b\x63onexion_up\x12\x05.ping\x1a\x04.ACK\x12,\n\x0fsend_parameters\x12\x13.message_parameters\x1a\x04.ACKb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moneda_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_PARAMETERS']._serialized_start=16
  _globals['_MESSAGE_PARAMETERS']._serialized_end=69
  _globals['_PING']._serialized_start=71
  _globals['_PING']._serialized_end=77
  _globals['_ACK']._serialized_start=79
  _globals['_ACK']._serialized_end=97
  _globals['_PARAMETERS']._serialized_start=99
  _globals['_PARAMETERS']._serialized_end=185
# @@protoc_insertion_point(module_scope)
